Validate result collection keys
qiime2/qiime2 pull request #700
Opened 2023-07-27 20:40 UTC by Oddant1

Ensure that result collection keys only contain the following characters: `A-Z`, `a-z`, `0-9`, `+`, `-`, `_`, and `.`.

Close #699

2023-07-28 14:43 UTC, gregcaporaso requested changes
This looks great @Oddant1 - just a couple of quick suggestions.

2023-07-28 14:43 UTC, gregcaporaso commented on qiime2/sdk/util.py
> +                       ' characters: A-Z, a-z, 0-9, +, -, _, and .')
```suggestion
                       ' characters: A-Z, a-z, 0-9, +, -, _, and .\n'
                       'The following key contains disallowed '
                       f'characters: {key}')
```

2023-07-28 14:43 UTC, gregcaporaso commented on qiime2/sdk/tests/test_result.py
> +                ' characters:.*'):
```suggestion
                ' characters:.*valid key'):
```

2023-07-28 14:43 UTC, gregcaporaso commented on qiime2/sdk/tests/test_result.py
> +                ' characters:.*'):
```suggestion
                ' characters:.*valid key'):
```

2023-07-28 14:43 UTC, gregcaporaso commented on qiime2/sdk/util.py
> +def validate_result_collection_key(key):
I recommend adding a couple of unit tests for this function itself, especially since it's public facing the in sdk.

2023-07-28 16:22 UTC, gregcaporaso approved these changes
@Oddant1, I ended up pushing a couple of commits while working on https://github.com/qiime2/q2-feature-table/pull/277. This all looks good to me, but you should review my changes.

2023-08-01 18:38 UTC, lizgehret reviewed
this lgtm @Oddant1 - once merge conflicts are resolved, i can get this one merged!

2023-08-02 20:57 UTC, gregcaporaso commented
I'm not sure why that flake8 issue came up here - should I move that commit over to a separate pull request?

2023-08-02 22:09 UTC, lizgehret approved these changes

2023-08-02 23:38 UTC, merged