Add assert_no_nans_in_tables
qiime2/qiime2 pull request #735
Opened 2023-11-30 18:43 UTC by Oddant1

Add testing util that asserts no tables in the given file contain NaNs

2023-11-30 18:44 UTC, Oddant1 commented
blocking qiime2/q2-demux#156

2023-12-11 20:55 UTC, lizgehret commented
Hey @Oddant1 - @ebolyen and I chatted about this, and the main thing that should be adjusted is the location of the new assertion. Since this assertion is being used only in the context of plugin actions, it should be moved from util.py -> plugins.py

2023-12-11 20:58 UTC, lizgehret requested changes
Hey @Oddant1 - @ebolyen and I chatted about this, and the main thing that should be adjusted is the location of the new assertion. Since this assertion is being used only in the context of plugin actions, it should be moved from util.py -> plugins.py

2023-12-12 18:00 UTC, ebolyen requested changes

2023-12-12 18:00 UTC, ebolyen commented on qiime2/plugins.py
> +    fh.seek(0)
Wrong plugin, sorry. We want the one which a plugin would import `qiime2.plugin.testing` or something like that.

2023-12-13 22:39 UTC, lizgehret commented
Tests all pass locally and I've tested `demux summarize` on the MP demux artifact, confirming that NaNs aren't present in the table. The test failure we see here is most likely due to a parsl version change (cc @Oddant1 to investigate), but this and the [chained q2-demux PR](https://github.com/qiime2/q2-demux/pull/156) are good to merge.

2023-12-13 22:40 UTC, merged