NEW: adds archive format v7
qiime2/qiime2 pull request #821
Opened 2024-12-03 21:59 UTC by lizgehret

2025-01-30 02:06 UTC, lizgehret commented
Okay well this isn't normal run time:
<img width="224" alt="Screen Shot 2025-01-29 at 7 04 44 PM" src="https://github.com/user-attachments/assets/ed075d18-4041-40bd-b0ba-a42dac2429c8" />

Seems weird that adding CPU flags would increase the run time by this much... will investigate further.

2025-02-05 23:11 UTC, lizgehret commented
To-do's:
- [ ] update archive_parser with v7 additions
- [ ] unit tests:
  - [ ] semantic versioning
  - [ ] conda-env.yaml file
  - [ ] datadir-size in action.yaml

2025-04-09 23:15 UTC, lizgehret commented on qiime2/core/archive/provenance_lib/parse.py
note that this isn't related to artifact format updates - but this was causing test failures due to nx.subgraph_view API changes.

2025-04-18 23:06 UTC, lizgehret commented
blocking https://github.com/qiime2/q2cli/pull/362

2025-04-21 03:55 UTC, lizgehret commented on qiime2/core/archive/provenance.py
> +
```suggestion
```

2025-04-21 20:38 UTC, ebolyen requested changes
Hey @lizgehret, this looks pretty good in general. There are a few places where we need to change some things, but I don't think any of this is going to look terribly different once fixed.

Some issues that aren't tied to any particular location:

~~1. Provenance won't group the annotations, so they end up scattered within the ancestors.~~ _this has been fixed_
2. Result.validate needs to exempt annotations from its list of validated files. (This is a good reason to move annotations out of provenance, otherwise life gets painful.)

2025-04-21 20:38 UTC, ebolyen commented on qiime2/core/annotate.py
> +    name : str\n
Does this cause any issues with numpydoc? I've not usually seen this.

2025-04-21 20:38 UTC, ebolyen commented on qiime2/core/annotate.py
> +            if annotation_type == 'Note':
We'll need an `else` branch, otherwise 7.0 reading 7.1 will produce an `UnboundLocalError` on `annotation`.

Raising an error is fine.

2025-04-21 20:38 UTC, ebolyen commented on qiime2/core/annotate.py
> +    def write_meta_yaml(self, annotations_dir,
We might want this to be private, as it will be visible on subclasses.

2025-04-21 20:38 UTC, ebolyen commented on qiime2/core/annotate.py
> +            'id': str(self.uuid),
I think these names should match to avoid confusion. I don't have a preference either way, we could go with `self.id` in the class or `'uuid'` in the yaml.

2025-04-21 20:38 UTC, ebolyen commented on qiime2/core/annotate.py
> +    def write(self, annotations_dir, root_result_uuid, referenced_result_uuid):
this probably also should be private

2025-04-21 20:38 UTC, ebolyen commented on qiime2/core/annotate.py
> +        # of some sort
what kind of validation are you thinking? it seems like this will work fine, we don't really care what they are writing.

2025-04-21 20:38 UTC, ebolyen commented on qiime2/core/archive/archiver.py
> +            for minor_version in range(minor, -1, -1):
neat! I've not seen this before, but it makes sense.

2025-04-21 20:38 UTC, ebolyen commented on qiime2/core/archive/archiver.py
> +                    return getattr(importlib.import_module(imp), fmt_cls)
there's a branch here that's correct implicitly, but it may be worth writing it out anyway:

When the for loop fails to find a match, we will skip out of the if and dead-end with a default return of None.
The for-else construct, as dumb as it would look, would spell it out to future readers that this path exists and is intentionally None.

2025-04-21 20:38 UTC, ebolyen commented on qiime2/core/archive/format/tests/test_util.py
> +            f'provenance/annotations/{note.uuid}/metadata.yaml',
I had assumed `annotations` would be in the root. Wouldn't this cause the existing grandcestor logic (which maybe you've changed already) to duplicate annotations within the `provenance/artifacts` directory?

2025-04-21 20:38 UTC, ebolyen commented on qiime2/core/archive/format/tests/test_util.py
> +                         f'^.*id: {note.uuid}.*name: mynote.*type: Note.*$')
It _might_ be worth matching on newlines between these, which I mention only because `.*` is usually a jerk.

2025-04-21 20:38 UTC, ebolyen commented on qiime2/core/archive/format/util.py
> +def write_checksums(directory, checksum_file, checksum_type):
wow. I can't believe this didn't exist already, this is a good place for it.

2025-04-21 20:38 UTC, ebolyen commented on qiime2/core/archive/format/v5.py
> +        cls.write_checksums(archive_record)
this is technically happening twice, once in v0, which looks up the implementation below, and then again here, which again looks up the implementation below. Net result is you run the checksums twice (the second time includes provenance as thats now written).

I would drop the call to write_checksums in v0's `write`.

2025-04-21 20:38 UTC, ebolyen commented on qiime2/core/archive/format/v7_0.py
> +
FYI: Stale docs, as there's an `id` (or maybe it'll be `uuid` field as well)

2025-04-21 20:38 UTC, ebolyen commented on qiime2/core/archive/format/v7_0.py
> +            provenance/
Tagging this pending discussion on root vs provenance.

2025-04-21 20:38 UTC, ebolyen commented on qiime2/core/archive/format/v7_0.py
> +        return f"{num:.1f} Yi{suffix}"
lol

2025-04-21 20:38 UTC, ebolyen commented on qiime2/core/archive/format/v7_0.py
> +                               data_initializer, provenance_capture)
V1 calls `super()` so this also suffers from the double-checksum problem. (It gets overwritten, so you don't notice it at the end, but if you throw a print in you'll see it).

2025-04-21 20:38 UTC, ebolyen commented on qiime2/core/archive/format/v7_0.py
> +                                  for filename in sorted(meta_files))
I _think_ you'll want to `filename.rsplit('-', 2)` to separate the versions to make it a technically installable environment.

2025-04-21 20:38 UTC, ebolyen commented on qiime2/core/archive/format/v7_0.py
> +                fh.write('error: no conda environment detected.\n')
would it be better to leave it empty, or otherwise drop the file? I'm not really sure what would make the most sense.

I'm fine with this if you prefer it. It's technically yaml, lol

2025-04-21 20:38 UTC, ebolyen commented on qiime2/core/archive/format/v7_0.py
> +        total_size = sum(path.stat().st_size for path in data_fp.iterdir()
This won't work when `data/` contains directories, as you'll only get the size of the filesystem's inode for a directory (which we don't care about), rather than the contents.

2025-04-21 20:38 UTC, ebolyen commented on qiime2/core/archive/provenance_lib/archive_parser.py
> +    '7.0': ParserV7
Are we missing logic to backtrack the prov-replay for future versions, `7.1` etc?

2025-04-21 20:38 UTC, ebolyen commented on qiime2/core/archive/tests/test_archiver.py
> +    def test_format_registry(self):
:100:

2025-04-21 20:38 UTC, ebolyen commented on qiime2/core/util.py
> +        cmd = ['sha512sum', str(filepath)]
Do we want to handle `shasum` or whatever the binary is on OS X? We could leave that for the future I suppose as the python fallback will always work.

2025-04-21 20:38 UTC, ebolyen commented on qiime2/core/archive/provenance_lib/_checksum_validator.py
> +    obs = checksum_directory_zip(zf, checksum_type=checksum_ext)
There's going to be an issue here, as the annotations are not exempted from the checksum list, so they will always look to be "added" files in the diff, and fail validation.

2025-04-21 20:38 UTC, ebolyen commented on qiime2/sdk/result.py
> +        result._read_annotations()
This isn't the only way to bring up an artifact, so the `_annotations` property won't always be set.

For example `cache.load('my-key')` would skip this line.

2025-04-21 20:38 UTC, ebolyen commented on qiime2/sdk/result.py
> +                    Annotation.load(os.path.join(annotations_dir, annotation))
We should probably be lazy here, either `Note` defers reading the note/content into memory, or `self._annotations` doesn't instantiate until requested. The latter is probably the best option for performance.

2025-04-21 20:38 UTC, ebolyen commented on qiime2/sdk/result.py
> +        result._read_annotations()
How about you make `_annotations` a `@property` so that you know that an instance exists, and you can memoize the results, then running `_read_annotations()` in all the correct spots matters way less.

2025-04-21 20:38 UTC, ebolyen commented on qiime2/core/util.py
> +    def metadata_constructor(loader, node, checksum_type):
We should have seen a failing test for this. The metadata_constructor is used a few lines under this and doesn't have any way to take `checksum_type` as an argument. Also, the metadata entries in provenance are still fixed to md5, so we can keep it md5 here as well.

2025-04-21 20:38 UTC, ebolyen commented on qiime2/sdk/result.py
> +        `write` method, while the Annotation instance handles everything else.
We probably don't need to include this in the user-facing docs, but putting it in a comment would be good.

2025-04-21 20:38 UTC, ebolyen commented on qiime2/sdk/result.py
> +        Annotation.write
unless you want users calling `Annotation.write` directly, I would leave this out and say nothing about it

2025-04-21 20:38 UTC, ebolyen commented on qiime2/sdk/result.py
> +                    'Namespace collision occurred when attempting to add '
I would go with "duplicate name" or something less technical here.

2025-04-21 20:38 UTC, ebolyen commented on qiime2/sdk/result.py
> +        checksums.pop(manifest, None)
Is there a situation where the annotation possesses a checksum already? I'm guessing its to do with moving a note between two artifacts?

2025-04-21 20:38 UTC, ebolyen commented on qiime2/sdk/result.py
> +                fh.write('\n')
It seems like this could all go in `Annotation.write` was it so that you can use `CHECKSUM_TYPE`? You could probably make those arguments to write (presuming it is converted to private) or just hardcode them to sha512.

2025-04-21 20:38 UTC, ebolyen commented on qiime2/sdk/result.py
> +        raise ValueError(f'No Annotation with name: "{name}" was found.')
This could be a KeyError if you wanted, but I don't care too much. It might suggest that `_annotations` would do better as a dict, so that you don't have to scan it each time looking for a given name, or a duplicate.

2025-04-21 20:38 UTC, ebolyen commented on qiime2/sdk/result.py
> +            If no Annotations are found associated with the Result.
This one might be better to not raise an error from, in which case you can implement it as:
```python
yield from self._annotations
```
and that's basically the whole method.

2025-04-21 20:38 UTC, ebolyen commented on qiime2/sdk/result.py
> +                             f'for Annotation with name: "{name}"')
weird, but probably a good idea.

2025-04-21 20:38 UTC, ebolyen commented on qiime2/core/archive/archiver.py
> +                 if x[0] != self._fmt.CHECKSUM_FILE)
We also need to exclude any annotations that may be present, otherwise it will raise an error here with "added" files.

2025-04-21 20:57 UTC, Oddant1 commented on qiime2/sdk/result.py
> +                    break
For this, we have already loaded the annotation and as such we should have its uuid right? So this should look something like 

`shutil.rmtree(os.path.join(annotations_dir, str(annotation_to_remove.uuid)))`

2025-04-21 20:57 UTC, Oddant1 commented on qiime2/sdk/result.py
> +            return iter(self._annotations)
I'd rather this be a tuple than an `iter`, but I don't have strong feelings

2025-04-21 20:57 UTC, Oddant1 commented on qiime2/sdk/result.py
> +        self._annotations = []
Given the amount of times we iterate over this looking for a given name, this should probably be a dict of {name: annotation}

2025-04-21 20:57 UTC, Oddant1 commented on qiime2/sdk/result.py
> +        # previous archive versions < 7.0
The implementation looks fine to me. I'd probably leave the comment just change its contents
```suggestion
        #  annotations_dir will be None for all archive versions < 7.0
```

2025-04-21 20:57 UTC, Oddant1 commented on qiime2/core/annotate.py
> +        # of some sort
If they use some file that can't be parsed into text as their annotation then if we attempt to read those contents later we will get an error, so we should probably make sure we can actually read the file as text before we use it as an annotation

2025-04-22 18:32 UTC, lizgehret commented on qiime2/sdk/result.py
> +            return iter(self._annotations)
@ebolyen says iter...

2025-04-22 20:57 UTC, lizgehret commented on qiime2/core/annotate.py
> +    name : str\n
discussed offline, will remove for now as we don't have time to test this before releasing

2025-04-22 21:14 UTC, lizgehret commented on qiime2/core/annotate.py
> +            'id': str(self.uuid),
i've updated this to self.id because this feels less confusing to an end user vs having uuid, root_result_uuid, and referenced_result_uuid all living in the same place

2025-04-22 21:17 UTC, lizgehret commented on qiime2/sdk/result.py
> +        result._read_annotations()
Evan and i worked on this offline and have implemented the latter suggestion

2025-04-22 21:49 UTC, Oddant1 commented on qiime2/sdk/result.py
> +            return iter(self._annotations)
@ebolyen has drank the LISP kool-aid :face_exhaling:

2025-04-23 19:58 UTC, lizgehret commented on qiime2/core/annotate.py
> +        # of some sort
ok i've added file size and content validation - so it can't exceed 10 MB and must be able to be read as utf-8

2025-04-23 21:16 UTC, lizgehret commented on qiime2/core/archive/format/tests/test_util.py
> +                         f'^.*id: {note.uuid}.*name: mynote.*type: Note.*$')
i've updated this to match on the first three lines & have adjusted write_meta_yaml to construct an orderedDict, so it's easier to match on multi-line content

2025-04-23 22:09 UTC, lizgehret commented on qiime2/core/archive/format/v7_0.py
> +                                  for filename in sorted(meta_files))
updated such that deps are now an installable env

2025-04-23 22:10 UTC, lizgehret commented on qiime2/core/archive/format/v7_0.py
> +                fh.write('error: no conda environment detected.\n')
i think i'd lean towards keeping it like this just so it's extra clear that a conda environment wasn't detected (even though i have no clue how we'd get here without a conda env lol)

2025-04-23 22:11 UTC, lizgehret commented on qiime2/core/archive/format/v7_0.py
> +                fh.write('error: no conda environment detected.\n')
that's also why i formatted it like this, so it would still be valid yaml 🤪

2025-04-23 22:44 UTC, lizgehret commented on qiime2/core/util.py
> +        cmd = ['sha512sum', str(filepath)]
i'll leave it for now since the python fallback should always work in the context of using QIIME 2 (like.... how would anything work without a valid python in a user's env)

2025-04-23 22:45 UTC, lizgehret commented on qiime2/sdk/result.py
> +                    Annotation.load(os.path.join(annotations_dir, annotation))
we worked on this offline & this has been fixed with an _annotation property on the result object

2025-04-23 22:48 UTC, lizgehret commented on qiime2/sdk/result.py
> +        Annotation.write
updated the whole docstring as a comment, so just leaving this as-is for us to reference in the future

2025-04-23 23:43 UTC, lizgehret commented on qiime2/core/archive/provenance_lib/archive_parser.py
> +    '7.0': ParserV7
Not sure I understand what you mean @ebolyen, can you clarify?

2025-04-24 00:00 UTC, lizgehret commented on qiime2/core/archive/format/v7_0.py
> +        total_size = sum(path.stat().st_size for path in data_fp.iterdir()
Hey @ebolyen yep you're totally right, I can def fix this - but I'm wondering if we ever expect to have subdirs under `data/`? I can't think of an example of where we'd see this off the top of my head. Or is this something we want to ensure is forwards compatible if this comes up in the future?

2025-04-24 00:13 UTC, lizgehret commented on qiime2/core/util.py
> +    def metadata_constructor(loader, node, checksum_type):
i'll add the default arg as md5 here - re: test failures, i'd like to chat about this for a few mins about this so i can add anything that's been previously missing

2025-04-24 00:35 UTC, lizgehret commented on qiime2/sdk/result.py
> +        checksums.pop(manifest, None)
i think i gaslit myself on this when i was testing, which is what led me to add this - but i just tested again on a fresh result and this isn't needed

2025-04-24 00:40 UTC, lizgehret commented on qiime2/sdk/result.py
> +                fh.write('\n')
this seemed like a reasonable place to add this since the checksum logic happens separately from the actual writing of the annotation - would you prefer it lives under `_write` though? if that feels more sensible i can move it there.

2025-04-24 17:43 UTC, lizgehret commented on qiime2/core/archive/provenance_lib/_checksum_validator.py
> +    obs = checksum_directory_zip(zf, checksum_type=checksum_ext)
ok this has been fixed - something that i'd also like to discuss though is why there were no test failures associated with this change

2025-04-24 18:00 UTC, lizgehret commented on qiime2/core/archive/archiver.py
> +                 if x[0] != self._fmt.CHECKSUM_FILE)
fixed from above comment re: annotations being excluded from checksum validation

2025-04-24 18:40 UTC, lizgehret commented on qiime2/sdk/result.py
> +        raise ValueError(f'No Annotation with name: "{name}" was found.')
that's fair; i'll modify `_annotations` accordingly along w/the endpoints that handle it

2025-04-24 18:58 UTC, lizgehret commented on qiime2/sdk/result.py
> +                    break
nice, yeah you're right Anthony. wrote this one too late in the day to be thinking clearly lol

2025-04-24 20:18 UTC, lizgehret commented on qiime2/core/archive/format/v7_0.py
> +        total_size = sum(path.stat().st_size for path in data_fp.iterdir()
evan and i discussed offline, this occurs in metagenomics Results & i will factor this functionality out into a helper to effectively test

2025-04-24 20:24 UTC, lizgehret commented on qiime2/core/archive/provenance_lib/_checksum_validator.py
> +    obs = checksum_directory_zip(zf, checksum_type=checksum_ext)
evan and i discussed this offline, this is expected bc none of the tests include the addition of annotations, which is where we'd expect to see the difference (before this change was made). i am going to add a test to assert an empty diff for this change.

2025-04-24 21:09 UTC, lizgehret commented on qiime2/core/util.py
> +    def metadata_constructor(loader, node, checksum_type):
evan and i chatted offline about this - there was a very unusual chain of confusion that's been resolved w/an added comment on how this constructor works wrt provenance's constructor. closing the case on this.

2025-04-24 21:14 UTC, lizgehret commented on qiime2/sdk/result.py
> +                fh.write('\n')
evan and i discussed offline and are going to leave this here until a future time dictates this being more sensible to move elsewhere... bc decision fatigue lol

2025-04-24 22:28 UTC, lizgehret commented on qiime2/core/archive/provenance_lib/archive_parser.py
> +    '7.0': ParserV7
discussed offline, similar logic to the get_format_class method within the archiver was added into the archive_parser within provlib

2025-04-24 23:58 UTC, lizgehret commented
Okay @ebolyen @Oddant1 this is ready for a (hopefully) final review!

2025-04-25 17:43 UTC, ebolyen approved these changes
Looks great! I think we can assume that `annotation/...` won't be in the root checksum, so there's not any need to ignore that path when loading the expected checksums from an archive. (This would also avoid logic that could somehow miss or ignore what the checksum says, which seems like something we would prefer not to do especially when signatures get involved.)

2025-04-25 17:43 UTC, ebolyen commented on qiime2/core/archive/archiver.py
> +                       )
```suggestion
```

We don't need this bit I think, since we won't write them into the checksum file in general.

2025-04-25 17:43 UTC, ebolyen commented on qiime2/core/archive/provenance_lib/_checksum_validator.py
> +            exp[fp] = checksum
```suggestion
        exp[fp] = checksum
```
Same here I think, we can trust the checksum file to not contain things we don't care about.

2025-04-25 17:43 UTC, ebolyen commented on qiime2/core/archive/provenance_lib/_checksum_validator.py
> +            exp[fp] = checksum
~~The section above however (for `obs = checksum...`) does need some updated logic. But I probably haven't gotten to the function definition for it yet.~~  Found it!

2025-04-25 17:43 UTC, ebolyen commented on qiime2/core/archive/provenance_lib/archive_parser.py
> +        if isinstance(artifact, pathlib.PosixPath):
yeah, that's probably a good idea

2025-04-25 17:43 UTC, ebolyen commented on qiime2/core/util.py
> +        if internal_path_parts and internal_path_parts[0] == 'annotations':
Here's the logic I was looking for, looks good!

2025-04-25 17:43 UTC, ebolyen commented on qiime2/sdk/result.py
> +        del annotations[name]
This all got way easier!

2025-04-25 17:50 UTC, Oddant1 commented on qiime2/sdk/result.py
> +        del annotations[name]
Look at you with you fancy __ methods. @ebolyen drank the LISP kool aid with the yield and the OOP kool aid with the __. All the kool aid

2025-04-25 18:00 UTC, lizgehret commented on qiime2/sdk/result.py
> +        del annotations[name]
i'll take this as a compliment @Oddant1

2025-04-25 18:35 UTC, ebolyen approved these changes

2025-04-25 18:45 UTC, ebolyen approved these changes

2025-04-25 19:16 UTC, merged